{% set version = "2.0.2" %}

package:
  name: jupyterlab-myst
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab-myst/jupyterlab_myst-{{ version }}.tar.gz
  sha256: b7bfa170f1bb15fde3177950bcebe7a48b02032d2b1a92261692c62f62469a89

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab >=4,<5
    - pip
    - python >=3.8
  run:
    - python >=3.8
  run_constrained:
    - jupyterlab >=4,<5

test:
  imports:
    - jupyterlab_myst
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupyterlab-myst.*v{{ version.replace(".", "\\.") }}.*enabled.*OK.*jupyterlab_myst" labextensions
  requires:
    - jupyterlab >=4,<5
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/executablebooks/jupyterlab-myst
  summary: A Myst renderer for JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab_myst/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - agoose77
    - bollwyvl
    - stevejpurves
