{% set version = "1.0.1" %}

package:
  name: jupyterlab-myst
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab-myst/jupyterlab_myst-{{ version }}.tar.gz
  sha256: 1fadd9800bb7f157abc719c589eddea898dae41a4f68e145b858fd67a5a8d540

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.4.0
    - jupyterlab >=3.4.7,<4
    - pip
    - python >=3.7
  run:
    - python >=3.7
  run_constrained:
    - jupyterlab >=3.1,<4.0.0a0

test:
  imports:
    - jupyterlab_myst
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupyterlab-myst.*v{{ version.replace(".", "\\.") }}.*enabled.*OK.*jupyterlab_myst" labextensions
  requires:
    - jupyterlab >=3.1,<4.0.0a0
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/executablebooks/jupyterlab-myst
  summary: A Myst renderer for JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab_myst/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - agoose77
    - bollwyvl
